In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.shape


array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
a.ndim

2

In [7]:
b = np.arange(6).reshape(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [11]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [12]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [13]:
b = np.array([(1.5,2,3), (4,5,6), (5,6)])
b

array([(1.5, 2, 3), (4, 5, 6), (5, 6)], dtype=object)

In [14]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [15]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
 np.empty( (2,3) )     

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [20]:
np.arange( 10, 35, 5 )

array([10, 15, 20, 25, 30])

In [21]:
np.arange( 0, 2, 0.3 )  

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [22]:
np.linspace( 0, 2, 9 )  

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [23]:
np.linspace( 0, 2, 11 )  

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [27]:
x = np.linspace( 0, 2* np.pi, 100 )
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [28]:
np.sin(x)

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [29]:
np.arange(6) 

array([0, 1, 2, 3, 4, 5])

In [30]:
np.arange(12).reshape(4,3) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [33]:
c = a-b
c

array([20, 29, 38, 47])

In [34]:
b**2

array([0, 1, 4, 9])

In [35]:
a<35

array([ True,  True, False, False])

In [36]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0], [3,4]] )
A * B  

array([[2, 0],
       [0, 4]])

In [39]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [40]:
b = np.random.random((2,3))
b

array([[0.87783876, 0.64925133, 0.54442441],
       [0.4990153 , 0.65431944, 0.80339047]])

In [41]:
a = np.ones((2,3), dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [43]:
a *= 3
a

array([[9, 9, 9],
       [9, 9, 9]])

In [45]:
a = np.random.random((2,3))
a

array([[0.78112013, 0.39416168, 0.25655303],
       [0.69762969, 0.89710209, 0.8613481 ]])

In [47]:
a = np.array( [20,30,40,50] )
a.sum()

140

In [49]:
a.min()

20

In [48]:
a.max()

50

In [55]:
d = np.array( [4,9,16,25] )
d

array([ 4,  9, 16, 25])

In [56]:
e = np.sqrt(d)
e

array([2., 3., 4., 5.])

In [57]:
d

array([ 4,  9, 16, 25])

In [58]:
np.exp(d)

array([5.45981500e+01, 8.10308393e+03, 8.88611052e+06, 7.20048993e+10])

In [60]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [70]:
a[0:3]

array([0, 1, 8])

In [71]:
def function1(x,y):
    return 10*x+y

np.fromfunction(function1, (5,4), dtype=int)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [72]:
aa = np.array( [[1,1],[0,1]] )
aa

array([[1, 1],
       [0, 1]])

In [75]:
aa.ravel()  # returns the array, flattened

array([1, 1, 0, 1])

In [76]:
a = np.floor(10*np.random.random((2,2)))
a

array([[9., 0.],
       [4., 9.]])

In [77]:
b = np.floor(10*np.random.random((2,2)))
b

array([[9., 4.],
       [5., 7.]])

In [78]:
np.vstack((a,b))

array([[9., 0.],
       [4., 9.],
       [9., 4.],
       [5., 7.]])

In [79]:
np.hstack((a,b))

array([[9., 0., 9., 4.],
       [4., 9., 5., 7.]])

In [80]:
a = np.floor(10*np.random.random((2,12)))
a

array([[6., 0., 1., 4., 7., 0., 9., 6., 0., 1., 0., 7.],
       [5., 0., 6., 9., 1., 6., 2., 8., 1., 4., 7., 4.]])

In [82]:
np.hsplit(a,3)   # Split a into 3

[array([[6., 0., 1., 4.],
        [5., 0., 6., 9.]]), array([[7., 0., 9., 6.],
        [1., 6., 2., 8.]]), array([[0., 1., 0., 7.],
        [1., 4., 7., 4.]])]

In [83]:
a = np.arange(12).reshape(3,4)
a > 4

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [84]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

array([[1., 2.],
       [3., 4.]])

In [85]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [86]:
x = np.float32(1.0)
x

1.0

In [89]:
np.char.islower( np.array( ['a', 'B'] ) )

array([ True, False])

In [95]:
np.median(np.array([[2, 2, 2, 5, 5, 5,]]))

3.5

In [96]:
np.std(np.array([[2, 2, 2, 5, 5, 5,]]))

1.5

In [97]:
np.var(np.array([[2, 2, 2, 5, 5, 5,]]))

2.25

In [98]:
np.average(np.array([[2, 2, 2, 5, 5, 5,]]))

3.5

In [99]:
np.mean(np.array([[2, 2, 2, 5, 5, 5,]]))

3.5